openapi: 3.0.3
info:
  title: CHS Delta API
  description: API specification for the chs-delta-api service
  version: "1.0"

paths:
  /delta/officers:
    $ref: 'officer-delta-spec.yml'
  /delta/officers/validate:
    $ref: 'officer-delta-spec.yml'
  /delta/insolvency:
    $ref: 'insolvency-delta-spec.yml'
  /delta/insolvency/delete:
    $ref: 'insolvency-delete-delta-spec.yml'
  /delta/insolvency/validate:
    $ref: 'insolvency-delta-spec.yml'
  /delta/charges:
    $ref: 'charges-delta-spec.yml'
  /delta/charges/delete:
    $ref: 'charges-delete-delta-spec.yml'
  /delta/charges/validate:
    $ref: 'charges-delta-spec.yml'
  /delta/disqualification:
    $ref: 'disqualification-delta-spec.yml'
  /delta/disqualification/delete:
    $ref: 'disqualification-delete-delta-spec.yml'
  /delta/disqualification/validate:
    $ref: 'disqualification-delta-spec.yml'
  /delta/company:
    $ref: 'company-delta-spec.yml'
  /delta/company/validate:
    $ref: 'company-delta-spec.yml'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Eric-Access-Token
      in: header

security:
  - ApiKeyAuth: []
