openapi: 3.0.3
info:
  title: CHS Delta API
  description: API specification for the chs-delta-api service
  version: "1.0"

paths:
  /delta/officers:
    $ref: 'officer-delta-spec.yml'
  /delta/officers/delete:
    $ref: 'officer-delete-delta-spec.yml'
  /delta/officers/validate:
    $ref: 'officer-delta-spec.yml'
  /delta/insolvency:
    $ref: 'insolvency-delta-spec.yml'
  /delta/insolvency/delete:
    $ref: 'insolvency-delete-delta-spec.yml'
  /delta/insolvency/validate:
    $ref: 'insolvency-delta-spec.yml'
  /delta/charges:
    $ref: 'charges-delta-spec.yml'
  /delta/charges/delete:
    $ref: 'charges-delete-delta-spec.yml'
  /delta/charges/validate:
    $ref: 'charges-delta-spec.yml'
  /delta/disqualification:
    $ref: 'disqualification-delta-spec.yml'
  /delta/disqualification/delete:
    $ref: 'disqualification-delete-delta-spec.yml'
  /delta/disqualification/validate:
    $ref: 'disqualification-delta-spec.yml'
  /delta/company:
    $ref: 'company-delta-spec.yml'
  /delta/company/delete:
    $ref: 'company-delete-delta-spec.yml'
  /delta/company/validate:
    $ref: 'company-delta-spec.yml'
  /delta/pscs:
    $ref: 'psc-delta-spec.yml'
  /delta/pscs/delete:
    $ref: 'psc-delete-delta-spec.yml'
  /delta/pscs/validate:
    $ref: 'psc-delta-spec.yml'
  /delta/exemption:
    $ref: 'psc-exemption-delta-spec.yml'
  /delta/exemption/delete:
    $ref: 'psc-exemption-delete-delta-spec.yml'
  /delta/exemption/validate:
    $ref: 'psc-exemption-delta-spec.yml'
  /delta/psc-statement:
    $ref: 'psc-statement-delta-spec.yml'
  /delta/psc-statement/validate:
    $ref: 'psc-statement-delta-spec.yml'
  /delta/psc-statement/delete:
    $ref: 'psc-statement-delete-delta-spec.yml'
  /delta/filing-history:
    $ref: 'filing-history-delta-spec.yml'
  /delta/filing-history/validate:
    $ref: 'filing-history-delta-spec.yml'
  /delta/filing-history/delete:
    $ref: 'filing-history-delete-delta-spec.yml'
  /delta/document-store:
    $ref: 'document-store-delta-spec.yml'
  /delta/document-store/validate:
    $ref: 'document-store-delta-spec.yml'
  /delta/registers:
    $ref: 'registers-delta-spec.yml'
  /delta/registers/validate:
    $ref: 'registers-delta-spec.yml'
  /delta/registers/delete:
    $ref: 'registers-delete-delta-spec.yml'
  /delta/acsp:
    $ref: 'acsp-profile-delta-spec.yml'
  /delta/acsp/validate:
    $ref: 'acsp-profile-delta-spec.yml'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Eric-Access-Token
      in: header

security:
  - ApiKeyAuth: []
